artifacts:
    - path: '**\*.nupkg'
build_script:
    - cmd: |
          git submodule update --init --recursive
          FOR /R %%f IN (*.csproj) DO nuget restore "%%f"
          msbuild Alkahest.sln
          FOR /r %%f IN (*.nuspec) DO nuget pack -Symbols "%%~pnf.csproj"
nuget:
    disable_publish_on_pr: true
image: Visual Studio 2019 Preview
notifications:
    - body: >-
          {
              "content": "[{{projectName}}](https://github.com/{{repositoryName}}) [{{commitId}}](https://github.com/{{repositoryName}}/commit/{{commitId}}) [{{buildVersion}}]({{buildUrl}}) **{{status}}**"
          }
      method: POST
      on_build_success: false
      on_build_failure: true
      on_build_status_changed: true
      provider: Webhook
      url: https://discordapp.com/api/webhooks/576898916860297226/AK3s4LaQZDhtBaLIORl2pcqqlN2xayVDSdpTN29ksyFc1lQdgHV7QV_VIT5OAf8PGqTx
pull_requests:
    do_not_increment_build_number: true
