after_build:
    - cmd: |
          forfiles /m *.proj /S /C "cmd /C msbuild @path"
          msbuild /t:Pack Alkahest.Core
artifacts:
    - path: 'Build\*.zip'
build:
    publish_nuget: true
    verbosity: detailed
before_build:
    - cmd: |
          git submodule update --init --recursive
          nuget restore
image: Visual Studio 2019 Preview
nuget:
    disable_publish_on_pr: true
pull_requests:
    do_not_increment_build_number: true
skip_tags: true
