after_build:
    - pwsh: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode `
              -Version 2.0
          msbuild Alkahest.Archive
artifacts:
    - path: 'Build\*.zip'
build:
    publish_nuget: true
    verbosity: detailed
before_build:
    - pwsh: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode `
              -Version 2.0
          markdownlint *.md **/*.md
          git submodule update `
              --init `
              --recursive
          nuget restore
image: Visual Studio 2019 Preview
install:
    - pwsh: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode `
              -Version 2.0
          npm install markdownlint-cli `
              -g
nuget:
    disable_publish_on_pr: true
pull_requests:
    do_not_increment_build_number: true
skip_tags: true
