artifacts:
    - path: '**\*.nupkg'
    - path: '**\*.zip'
build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: detailed
before_build:
    - cmd: |
          git submodule update --init --recursive
after_build:
    - cmd: |
          forfiles /m *.proj /S /C "cmd /C msbuild @path"
nuget:
    disable_publish_on_pr: true
image: Visual Studio 2019 Preview
pull_requests:
    do_not_increment_build_number: true
